server {
    listen 80;
    server_name nexusiotenergy.com.br www.nexusiotenergy.com.br;

    root /var/www/nexus-iot-energy-landing;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
